### ISSUE TITLE
Ellipsoid meshing

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [dengwirda/jigsaw-python#21]
@dengwirda are there any quick guide documents/papers anywhere for ellipsoid meshing using Jigsawpy? I'm trying a global meshing where I'd like to exclude lands from the mesh domain, but I get strange results. Even if I try meshing regional, but ellipsoidal, I still don't get what I'm expecting.

In the *regional* case I'm testing, my inputs are `geom` and `opts` (**no** `hfun` or `init`). I set `vert2` and `edge2` (and `radii`, `ndims`, `mshID`) on the `geom`, where my `vert2` is lon/lat in radians. For large values of lon/lat in the input the resulting mesh is empty.

For the results, in cases where it works for me, I get `vert3` in the output mesh that I convert using `R3toS2` to convert to lon/lat.

Are the any gotchas etc. that I should be aware of when using ellipsoidal mesh by jigsaw?

Thank you in advance

**Comment by dengwirda** [comment]
@SorooshMani-NOAA the [jigsaw tutorials](https://github.com/dengwirda/jigsaw-geo-tutorial) include a range of examples, both on the spheroid and in flat domains, so hopefully this is a good place to start.

For the spheroidal case there's not any culling done, since these kind of meshes are typically used for both ocean and land-surface (and/or atmospheric) modelling. In E3SM, meshes of the full sphere are typically culled separately, using a coastline database or remapped elevation data.

Depending on your application, it may be worth keeping the stereographic workflow (described at the end of the tutorial) in mind --- this is typically a useful way to build regional meshes for ocean models.

**Comment by SorooshMani-NOAA** [comment]
Thank you for this information, this is helpful
