### ISSUE TITLE
Is it possible that a too large numthread can make rDT slower?

### ISSUE THREAD

**Issue by jreniel** [dengwirda/jigsaw-python#25]
Hi!
I'm using a server with the following characteristics:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    1
Core(s) per socket:    64
Socket(s):             2
NUMA node(s):          2
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7702 64-Core Processor
```
I've noticed that as I increase the numthread count, rDT actually becomes considerably slower.
For example using numthread=64 takes over 3 days to complete rDT, but the same example works in a matter of minutes if I use numthread=16.

Has anyone else noticed this behavior? Are the any potential causes for this?
Thanks!
-J.

**Comment by dengwirda** [comment]
@jreniel, I would hope that runtimes don't blow out with increasing numthreads --- obviously that's not the intention!
Would you mind attaching the `*.log` files for the two cases here? A few initial thoughts:
- The initial refinement step in jigsaw is not currently thread parallel, so that time should be roughly constant.
- (Parts of) the optimisation step are thread parallel, so that's where the speedup is expected.
- There is logic to scale the number of threads actually used based on problem size, with the `numthread` user-opt the upper bound. This is intended to prevent the behaviour that you're seeing where too many threads are used at a given mesh size...
- It's unlikely that the `openmp` based implementation will scale up continuously, and in my own tests the best speedup I achieved was around 20x (for the particular kernel that's been parallelised) on 32 threads.
- The presence of multiple NUMA nodes can complicate matters. What behaviour do you see with `numthread=32`?

**Comment by jreniel** [comment]
Thanks @dengwirda, how do I output the log files (negative verbosity?)
I think it has a sweet spot for 32 threads. But to me what's really interesting is that for a "small" problem I am trying to compute, when using more than 32 threads the rDT part becomes ridiculously slow after 32 threads, which I just find as odd behavior so I had to report this observation. I haven't benchmarked this with actual timing, but maybe outputting the logfiles can help me double check if my observations are substantiated.

**Comment by jreniel** [comment]
Ok, I figured out why my setup was taking an impossibly long time. It had to do with my setup.
Thanks!
